/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Appointment
 */
export interface Appointment {
    /**
     * 
     * @type {number}
     * @memberof Appointment
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Appointment
     */
    customerId?: number;
    /**
     * 
     * @type {number}
     * @memberof Appointment
     */
    userId?: number;
    /**
     * 
     * @type {Date}
     * @memberof Appointment
     */
    appointmentDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Appointment
     */
    reminderDate?: Date;
}

/**
 * Check if a given object implements the Appointment interface.
 */
export function instanceOfAppointment(value: object): value is Appointment {
    return true;
}

export function AppointmentFromJSON(json: any): Appointment {
    return AppointmentFromJSONTyped(json, false);
}

export function AppointmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Appointment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'appointmentDate': json['appointmentDate'] == null ? undefined : (new Date(json['appointmentDate'])),
        'reminderDate': json['reminderDate'] == null ? undefined : (new Date(json['reminderDate'])),
    };
}

export function AppointmentToJSON(json: any): Appointment {
    return AppointmentToJSONTyped(json, false);
}

export function AppointmentToJSONTyped(value?: Appointment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'customerId': value['customerId'],
        'userId': value['userId'],
        'appointmentDate': value['appointmentDate'] == null ? undefined : ((value['appointmentDate']).toISOString().substring(0,10)),
        'reminderDate': value['reminderDate'] == null ? undefined : ((value['reminderDate']).toISOString().substring(0,10)),
    };
}

