/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthReq
 */
export interface AuthReq {
    /**
     * 
     * @type {string}
     * @memberof AuthReq
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthReq
     */
    password?: string;
}

/**
 * Check if a given object implements the AuthReq interface.
 */
export function instanceOfAuthReq(value: object): value is AuthReq {
    return true;
}

export function AuthReqFromJSON(json: any): AuthReq {
    return AuthReqFromJSONTyped(json, false);
}

export function AuthReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthReq {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function AuthReqToJSON(json: any): AuthReq {
    return AuthReqToJSONTyped(json, false);
}

export function AuthReqToJSONTyped(value?: AuthReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

