/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactEmailReq
 */
export interface ContactEmailReq {
    /**
     * 
     * @type {number}
     * @memberof ContactEmailReq
     */
    contactId?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContactEmailReq
     */
    email?: Array<string>;
}

/**
 * Check if a given object implements the ContactEmailReq interface.
 */
export function instanceOfContactEmailReq(value: object): value is ContactEmailReq {
    return true;
}

export function ContactEmailReqFromJSON(json: any): ContactEmailReq {
    return ContactEmailReqFromJSONTyped(json, false);
}

export function ContactEmailReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactEmailReq {
    if (json == null) {
        return json;
    }
    return {
        
        'contactId': json['contactId'] == null ? undefined : json['contactId'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function ContactEmailReqToJSON(json: any): ContactEmailReq {
    return ContactEmailReqToJSONTyped(json, false);
}

export function ContactEmailReqToJSONTyped(value?: ContactEmailReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contactId': value['contactId'],
        'email': value['email'],
    };
}

