/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';

/**
 * 
 * @export
 * @interface EventListRsp
 */
export interface EventListRsp {
    /**
     * 
     * @type {Array<Event>}
     * @memberof EventListRsp
     */
    evReminder?: Array<Event>;
    /**
     * 
     * @type {Array<Event>}
     * @memberof EventListRsp
     */
    evAppointment?: Array<Event>;
}

/**
 * Check if a given object implements the EventListRsp interface.
 */
export function instanceOfEventListRsp(value: object): value is EventListRsp {
    return true;
}

export function EventListRspFromJSON(json: any): EventListRsp {
    return EventListRspFromJSONTyped(json, false);
}

export function EventListRspFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventListRsp {
    if (json == null) {
        return json;
    }
    return {
        
        'evReminder': json['evReminder'] == null ? undefined : ((json['evReminder'] as Array<any>).map(EventFromJSON)),
        'evAppointment': json['evAppointment'] == null ? undefined : ((json['evAppointment'] as Array<any>).map(EventFromJSON)),
    };
}

export function EventListRspToJSON(json: any): EventListRsp {
    return EventListRspToJSONTyped(json, false);
}

export function EventListRspToJSONTyped(value?: EventListRsp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'evReminder': value['evReminder'] == null ? undefined : ((value['evReminder'] as Array<any>).map(EventToJSON)),
        'evAppointment': value['evAppointment'] == null ? undefined : ((value['evAppointment'] as Array<any>).map(EventToJSON)),
    };
}

