/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterCustomerReq
 */
export interface RegisterCustomerReq {
    /**
     * 
     * @type {string}
     * @memberof RegisterCustomerReq
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCustomerReq
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCustomerReq
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCustomerReq
     */
    vatNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCustomerReq
     */
    company?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RegisterCustomerReq
     */
    email?: Array<string>;
}

/**
 * Check if a given object implements the RegisterCustomerReq interface.
 */
export function instanceOfRegisterCustomerReq(value: object): value is RegisterCustomerReq {
    return true;
}

export function RegisterCustomerReqFromJSON(json: any): RegisterCustomerReq {
    return RegisterCustomerReqFromJSONTyped(json, false);
}

export function RegisterCustomerReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterCustomerReq {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'vatNumber': json['vatNumber'] == null ? undefined : json['vatNumber'],
        'company': json['company'] == null ? undefined : json['company'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function RegisterCustomerReqToJSON(json: any): RegisterCustomerReq {
    return RegisterCustomerReqToJSONTyped(json, false);
}

export function RegisterCustomerReqToJSONTyped(value?: RegisterCustomerReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'phoneNumber': value['phoneNumber'],
        'vatNumber': value['vatNumber'],
        'company': value['company'],
        'email': value['email'],
    };
}

