/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistrationReq
 */
export interface RegistrationReq {
    /**
     * 
     * @type {string}
     * @memberof RegistrationReq
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationReq
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationReq
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationReq
     */
    lastName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RegistrationReq
     */
    email?: Array<string>;
}

/**
 * Check if a given object implements the RegistrationReq interface.
 */
export function instanceOfRegistrationReq(value: object): value is RegistrationReq {
    return true;
}

export function RegistrationReqFromJSON(json: any): RegistrationReq {
    return RegistrationReqFromJSONTyped(json, false);
}

export function RegistrationReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationReq {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function RegistrationReqToJSON(json: any): RegistrationReq {
    return RegistrationReqToJSONTyped(json, false);
}

export function RegistrationReqToJSONTyped(value?: RegistrationReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
    };
}

